### ISSUE TITLE
unreachable on certain input

### ISSUE THREAD

**Issue by Enter-tainer** [mitex-rs/mitex#112]
```
\left\/\frac 1 2\right)
```

![Screenshot_2024-01-11-18-23-47-543_com.microsoft.emmx.jpg](https://github.com/mitex-rs/mitex/assets/25521218/7e69a77b-55bb-4929-aa02-0e084085985b)

**Comment by Enter-tainer** [comment]
maybe use fuzzer to test parser & lexer

**Comment by Myriad-Dreamin** [comment]
agreed

**Comment by Enter-tainer** [comment]
I've tried using afl.rs to fuzz risingwave before. I can set up simliar thing when I leave work

**Comment by Myriad-Dreamin** [comment]
I prefer libfuzzer-sys, which uses llvm and much more lightweight.

**Comment by Myriad-Dreamin** [comment]
https://github.com/rust-fuzz/cargo-fuzz

**Comment by Enter-tainer** [comment]
actually afl is easier because it works in stable rust, while libfuzzer requires nightly

**Comment by Enter-tainer** [comment]
minimized using afl:
```
\left\0
```
```
\end{}
```
crashes mitex

**Comment by Enter-tainer** [comment]
#113

**Comment by Myriad-Dreamin** [comment]
more comment: Reaching a panic-free MiTeX has a slightly lower priority than producing a design of converting complex environments in text mode. This is for enrich corpora of typst documents. For that goals with higher priority, for example, we would like to convert a large set of TeX papers to typst.

Therefore, the underlying parser and converter may still change a lot. To do that, we want to collect frequently used commands and summarize a closest model to typst elements:

+ https://authors.acm.org/proceedings/production-information/accepted-latex-packages
+ https://mirror-hk.koddos.net/CTAN/info/latex-doc-ptr/latex-doc-ptr.pdf
+ https://blog.writefull.com/the-100-most-frequent-latex-commands/

**Comment by Enter-tainer** [comment]
agree. most panics are from broken latex input. they seem not happen in valid inputs

**Comment by Myriad-Dreamin** [comment]
close by https://github.com/mitex-rs/mitex/pull/113 and https://github.com/mitex-rs/mitex/commit/22e87fb48e65e56ee576519e400a00f4292aaa4c
