### ISSUE TITLE
`textcolor` crashed in 0.2.0

### ISSUE THREAD

**Issue by HeZeBang** [mitex-rs/mitex#115]
Example: 

```
#import "@preview/mitex:0.2.0": *
#mitex(`\textcolor{orange}{test}`)
```

caused this problem:

```
Unknown variable: tex
```

**Comment by OrangeX4** [comment]
Thanks, this is a typo, I've fixed it. It will be fixed in version 0.2.1.

https://github.com/typst/packages/pull/343

**Comment by Myriad-Dreamin** [comment]
Should it close since 0.2.1 is published?

**Comment by OrangeX4** [comment]
Yes, i will close it.
