### ISSUE TITLE
`\lvert` `\rvert` 's space looks strange

### ISSUE THREAD

**Issue by Enter-tainer** [mitex-rs/mitex#49]
```
#mitex(`
\lvert a \rvert
`
) $ abs(a) $
```

![image](https://github.com/OrangeX4/mitex/assets/25521218/8597df41-e3b6-466b-b3ba-02977ee76ee6)

might be hard to handle

**Comment by Enter-tainer** [comment]
I've just sort oiwiki equations by length and check about top 10% of them. Most of them looks fine!

**Comment by Myriad-Dreamin** [comment]
btw, it is the output of texmath

![image](https://github.com/OrangeX4/mitex/assets/35292584/6287cd2c-04cd-45fe-b194-13e7d049000f)

**Comment by OrangeX4** [comment]
This issue is a bit difficult to deal with, and I need to take into account the spaces before and after the symbols, and I'll see if there's any way to improve it later.

**Comment by OrangeX4** [comment]
How about something like:

```typst
#let vert = math.class("closing", sym.bar.v)

$ z + vert x vert + y $
```

![image](https://github.com/OrangeX4/mitex/assets/34951714/c8303c1d-fe33-4c5b-b761-4a03f800576e)

But this results in a slight asymmetry.

**Comment by Enter-tainer** [comment]
this is not optimal because vert can be used for other purpose

**Comment by OrangeX4** [comment]
Yes, it's hard to deal with

**Comment by Myriad-Dreamin** [comment]
![image](https://github.com/mitex-rs/mitex/assets/35292584/78918ddc-b3f7-4e10-bb4c-0b7cb3e10f4e)

**Comment by Myriad-Dreamin** [comment]
This looks correct

**Comment by Enter-tainer** [comment]
how does tex determine which vert is opening and which vert is close?

**Comment by Enter-tainer** [comment]
> how does tex determine which vert is opening and which vert is close?

I miss read. for lvert and rvert, it is easy to determin open and close. The hard thing is something like `$|a+b|$`
