### ISSUE TITLE
Provide a native CLI program to convert LaTeX source into typst source.

### ISSUE THREAD

**Issue by KDr2** [mitex-rs/mitex#71]
If I get it correctly, for the time being, mitex only works as a WASM module and thus only works on the typst web app, but not for the CLI.

It would be better to provide a CLI program that runs like:
```
mitex -i foo.tex -o foo.typ
```

Then we can deal with the typst source with typst-cli.

Another benefit of this is that we can easily build a testset with a bunch of TeX sources, which will largely assure the quality and stability of mitex.

**Comment by Myriad-Dreamin** [comment]
It is in plan but we may not have sufficient bandwidth to implement that feature.
Also I prefer following interface (aligned with typst-cli), since we may have some other commands (such as `mitex spec generate`):
```bash
mitex compile foo.tex
# is same as
mitex compile foo.tex -o foo.typ
```

Accurately, mitex is a transpiler but we still use `compile` here.

---

Btw, you can also process tex files by typst scripts:

```typ
#import "/packages/mitex/lib.typ": *
// or #import "/@preview/mitex:0.1.0": *

#let tex-files = json("list-of-tex-files.json");
#let output = tex-files.map(path => mitex-convert(read(path)))
#metadata(output) <transpiled>
```

Then you can get it by shell command:
```bash
typst query --root . main.typ "<transpiled>" > output.json
```

**Comment by Enter-tainer** [comment]
> mitex only works as a WASM module and thus only works on the typst web app, but not for the CLI.

That's not true. WASM module is uniformly supported in typst webapp and cli

**Comment by KDr2** [comment]
> That's not true. WASM plugin is uniformly supported in typst webapp and cli. But i agree that it is good to have a mitex-cli 

That's great, so there's a WASM runtime embedded in typst-cli?

**Comment by OrangeX4** [comment]
Yes, typst has its own wasm runtime.

**Comment by KDr2** [comment]
> Yes, typst has its own wasm runtime.

Oh I found it, it's [wasmi](https://github.com/paritytech/wasmi).

**Comment by KDr2** [comment]
> you can also process tex files by a typst script

Thanks, I will try this first.

**Comment by OrangeX4** [comment]
But at the moment MiTeX only supports math equations, and we are ready to develop text mode in the next step.

**Comment by KDr2** [comment]
> But at the moment MiTeX only supports math equations, and we are ready to develop text mode in the next step.

Roger.
