### ISSUE TITLE
Distinguish between inline equations and block equations

### ISSUE THREAD

**Issue by OrangeX4** [mitex-rs/mitex#73]
Currently, Lexer treats a single dollar sign and multiple dollar signs as the same token, so we can't distinguish between an inline equation and a block equation.

https://github.com/mitex-rs/mitex/blob/41a666c4e205549bd27c9a778b2c48b2fc706bdf/crates/mitex-lexer/src/lib.rs#L433-L434

**Comment by Myriad-Dreamin** [comment]
This can be distinguished by checking the content of the dollar token
