### ISSUE TITLE
Extra zws in frac

### ISSUE THREAD

**Issue by Enter-tainer** [mitex-rs/mitex#96]
<img width="508" alt="image" src="https://github.com/mitex-rs/mitex/assets/25521218/32cc32ee-8550-461f-a717-6fd0fd656935">

```latex
{\frac{a}{b}}^T
```
should look like this(with braces removed)
<img width="81" alt="image" src="https://github.com/mitex-rs/mitex/assets/25521218/7b712e73-4f6a-4bab-9a90-3e25610b5c4a">

**Comment by Myriad-Dreamin** [comment]
deduplicated as `{t}^T`
